version: "3.3"

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#RUN python /code/manage.py makemigrations
#RUN python /code/manage.py migrate
# python manage.py makemigrations && python manage.py migrate &&