# Generated by Django 4.0.1 on 2022-01-14 22:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('READ_ONLY', 'READ_ONLY'), ('FULL_MEMBERS', 'FULL_MEMBERS'), ('SUPER_ADMIN', 'SUPER_ADMIN')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 14, 22, 34, 41, 173798))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 1, 14, 22, 34, 41, 173821))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('jwt', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
